name: Echo only
on: 
 push: 
   branches:
   - main
env: 
  APP_NAME: "jfld"
  VERSION: "4.67"
jobs:
  create_the_message:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the command
      run: echo "we are eching the message ${{env.APP_NAME}} and version ${{env.VERSION}}"
