name: GitHub pipeline
on: 
  push: 
    branch: 		
      - main
env:	
  PROD_ID: 3
  VERSION: 3
jobs:	
  echo-hello-words:
    runs-on: "ubuntu-latest"
    steps:
    - name: echo env
      run: "echoing helow from ${{env.PROD_ID}} and version is ${{env.VERSION}} "  
